name: NASA Project CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build: 
    env: 
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    strategy: 
      matrix:
        node-version: [14.x, 16.x]
        mongo-version: ['4.4']
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB from GitHub Actions
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongo-version: ${{ matrix.mongo-version }}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test 